name: glypher
main: dev.LmVictor20.glypher.GlypherPlugin
version: 1.0.0-SNAPSHOT
api-version: '1.21'
depend: [ProtocolLib]

commands:
  menuconfig:
    description: Configure glyph-based menu titles
    usage: /menuconfig [list|saved]
    aliases: [mcfg]

permissions:
  glypher.menuconfig.use:
    description: Allows opening menu configuration wizard
    default: op
  glypher.menuconfig.list:
    description: Allows viewing saved menu presets
    default: op
  glypher.menuconfig.delete:
    description: Allows deleting saved menu presets
    default: op
